---
# - name: Install required package
#   package:
#     name: python3-passlib
#     state: present
#   become: True

- name: Create tmp directory to store OpenShift binaries
  tempfile:
    state: directory
    suffix: "htpasswd"
  register: tempdiroutput
  tags:
  - tempdir

- name: Get existing users
  block:
  - name: Get current htpasswd secret
    command: "oc -n openshift-config get secret '{{ htpasswd_secret_name }}' -o jsonpath='{.data.htpasswd}'"
    register: htpasswd_secret_out
  

  - name: Create htpasswd file with content
    copy:
      dest: "{{ tempdiroutput.path }}/ocp4-htpasswd"
      content: "{{ htpasswd_secret_out.stdout | b64decode }}"

  rescue:
  - name: Create empty htpasswd_content fact
    set_fact:
      htpasswd_content: ""

- name: Create htpasswd file for user
  community.general.htpasswd:
    path: "{{ tempdiroutput.path }}/ocp4-htpasswd"
    name: "{{ username }}"
    password: "{{ password }}"
    mode: 0644

- name: Read htpasswd content
  set_fact:
    new_htpasswd_content: "{{ lookup('file', tempdiroutput.path + '/ocp4-htpasswd') }}"

- name: Create or update secret
  shell: |
    oc -n openshift-config create secret generic {{ htpasswd_secret_name }} --from-file=htpasswd={{ tempdiroutput.path }}/ocp4-htpasswd --dry-run=client -o yaml | oc apply -f -

- name: Delete tempdir
  file:
    path: "{{ tempdiroutput.path }}"
    state: absent

- debug: msg="content {{ new_htpasswd_content }}"

